DROP TABLE IF EXISTS Rentals;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Cars;

CREATE TABLE Customers (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(300) NOT NULL,
  address VARCHAR(500) NOT NULL,
  phoneNumber VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isActive BOOLEAN NOT NULL DEFAULT 1

) COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS Cars;
CREATE TABLE Cars (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(300) NOT NULL,
  numberPlate VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL,
  brand VARCHAR(200),
  model VARCHAR(100),
  modelYear INT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isActive BOOLEAN NOT NULL DEFAULT 1

) COLLATE=utf8_unicode_ci;

CREATE TABLE Rentals (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customerID INT NOT NULL,
  carID INT NOT NULL,
  rentalStartAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  plannedRentalEndAt TIMESTAMP NOT NULL,
  comment VARCHAR(500), 
  kilometrage FLOAT,
  reurnedAT TIMESTAMP,

  FOREIGN KEY (customerID) REFERENCES Customers(id),
  FOREIGN KEY (carID) REFERENCES Cars(id)
) COLLATE=utf8_unicode_ci;